### ISSUE TITLE
Question about installation of InstaFlow and PerFlow

### ISSUE THREAD

**Issue by blistick** [feifeiobama/RectifID#1]
Thank you for this work! I have a simple question about installation. I see that there are empty InstaFlow and piecewise-rectified-flow subfolders, but I don't understand how to properly install those modules. I tried cloning their repos into each folder, but I still get "module not found" errors when I try the single_person_perflow Jupyter notebook. I'm sure there is some simple step I'm missing. Any tips would be greatly appreciated!

**Comment by feifeiobama** [comment]
You can directly run `git clone --recursive`, or directly download their code into InstaFlow and picewise_rectified_flow subfolders. Note that I used "_" in "piecewise_rectified_flow" instead of "-".

**Comment by feifeiobama** [comment]
You can directly run `git clone --recursive`, or download their code into InstaFlow and picewise_rectified_flow subfolders. Note that I used "_" in "piecewise_rectified_flow" instead of "-".

**Comment by blistick** [comment]
Thank you, @feifeiobama! It was the underscores verses dashes that tripped me up.
