### ISSUE TITLE
Enviroment Installation Guide

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#2]
Can you please provide full list of dependencies wtih pip freeze > req.txt , I cannot install the environment, too much conflict happens.

**Comment by feifeiobama** [comment]
I do not have the environment at the moment (my server keeps getting reset). But I have always used the following commands for installation after each reset, which seem to work fine:
```shell
pip install insightface onnx2torch kornia deepface
pip install typing-extensions --upgrade
pip install diffusers --upgrade
pip uninstall onnxruntime-gpu
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```
Note that the last line depends on your cuda version.

**Comment by Oguzhanercan** [comment]
The problem occurs due to the "and the dependencies of PeRFlow" part. If I skip that part (when I look at your installation guide, looks like I do not need") is it gonna work correctly?

**Comment by feifeiobama** [comment]
Yes, I think most of PeRFlow's dependencies are just common packages. As far as I remember, I only ran into an error when moving to another environment where I had to install `peft` and `accelerate` additionally.

**Comment by Oguzhanercan** [comment]
thanks, I solved the problem.
