### ISSUE TITLE
Model 2RFlow does not working

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#4]
Hi, when I try to run the model for 2RFLow option, I get the error below.

return self._forward(self.pipe, prompt=prompt, height=self.size, width=self.size, num_inference_steps=num_steps, guidance_scale=self.guidance_scale,
TypeError: __call__() got an unexpected keyword argument 'callback_on_step_end'

**Comment by feifeiobama** [comment]
Please refer to this line in the README.md:
https://github.com/feifeiobama/RectifID/blob/main/README.md?plain=1#L16

**Comment by Oguzhanercan** [comment]
Thanks a lot, right now I am testing the model with different face recognition models, it performs really well.
