### ISSUE TITLE
About Face Recognation Benchmarks and Inference Time Optimization

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#5]
Hi, thanks for great work, I have tested the performance of the model on face recognition. It performs better than every other model. But inference time is really long. Is there any recommendation about how to make inference of model faster?

**Comment by feifeiobama** [comment]
Our method involves repeated backpropagation and is therefore slow during inference. We recommend some recent backpropagation-free methods for potential efficiency improvements:
* RB-Modulation: Training-Free Personalization of Diffusion Models using Stochastic Optimal Control ([link](https://arxiv.org/abs/2405.17401)).
* Derivative-Free Guidance in Continuous and Discrete Diffusion Models with Soft Value-Based Decoding ([link](https://arxiv.org/abs/2408.08252)).

**Comment by Oguzhanercan** [comment]
@feifeiobama thanks a lot.
