### ISSUE TITLE
Theorical Understanding of RectifID

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#6]
Hi, it was hard to understand, but intuitively I was able to understand the paper (I spent huge time to understand equations). Can you suggest me the relative books or courses to understand differential eqs in context of diffusion models, flow based diffusion models, velocity concept?

**Comment by feifeiobama** [comment]
I recommend reading the original papers (DDPM, Score SDE, EDM, Rectified Flow, Flow Matching), but the following material may also be helpful:
* diffusion model: https://yang-song.net/blog/2021/score/
* flow model: https://youtube.com/watch?v=5ZSwYogAxYg

**Comment by Oguzhanercan** [comment]
I have already read relative papers, but still I did not fully understand the subject in depth.

**Comment by feifeiobama** [comment]
Put faith in yourself :)

**Comment by Oguzhanercan** [comment]
working on it :)
