### ISSUE TITLE
is it possible to run the model at 1 step?

### ISSUE THREAD

**Issue by Oguzhanercan** [feifeiobama/RectifID#7]
Hi, I am trying to run the model at one step. Instead of perflow, I am using a diffusion model which distilled to 1 step (bytedance sdxl 1 step, with LCMScheduler), so since it is one step, I believe that theoretically it is okey because the flow is straight. But when I try it, I get an error:
RuntimeError: output with shape [1,4,64,64] does not match the broadcast shape [0,4,64,64]. 

```callback_kwargs['latents'] += latents_last[i:(i+1)].detach() - callback_kwargs['latents'].detach()```

for the callback function. And this is related to the assignment of step to 1.

**Comment by feifeiobama** [comment]
Yes, it is possible. However, I have tried the model you mentioned. For SDXL-lightning and LCM, they're distilled in a way that significantly reduces generation diversity. It is very difficult to guide their trajectories to produce the desired output.

The following few-step models strike a better balance between efficiency and diversity: PeRFlow, SD-Turbo and PCM.

**Comment by Oguzhanercan** [comment]
Thanks for sharing your experimental results. I want to try it by myself because I want to test it on my test set (Face recognition) and record the benchmarks of the model for my presentation (about  face recognition on synthetic data). If you have any insights about the error, can you explain me how to solve it? 

Also I wonder that which scheduler did you used while experimenting other models than perflow?

**Comment by feifeiobama** [comment]
I have not yet identified the cause of the error. Since this code is mainly tested under few-step diffusion models, I suggest simply using 4-step SDXL-lightning for evaluation.

I experimented with the default scheduler in their original examples, e.g. Euler scheduler for SDXL-lightning and TCD scheduler for PCM.

**Comment by Oguzhanercan** [comment]
I want to share my finding, if you use more than 1 face recognition network, generation results gets better (In this setting, for black-white photos, model collapses to child photo).

**Comment by feifeiobama** [comment]
> I want to share my finding, if you use more than 1 face recognition network, generation results gets better (In this setting, for black-white photos, model collapses to child photo).

Thank you for sharing the new finding, it makes perfect sense.
